### ISSUE TITLE
[Bug] [General] Settings Window Extra Padding On App Initialization

### ISSUE THREAD

**Issue by Enubia** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#487] opened 2023-08-18 09:40 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Window content is not aligned to the boundaries on initial start

# Current Behavior

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/44695100/5655e8eb-17fa-46fd-8dd3-535293a3563d)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. launch app
2. look at window
3. content not aligned
4. click on advanced tab
5. now it's aligned properly

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 2.0.0
* Operating System: Windows 11 22H2 DotNet 7.0
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by HiMarioLopez** [comment] 2023-08-18 14:01
ye marked this as low priority bug for now

related to this: https://stackoverflow.com/questions/29207331/wpf-window-with-custom-chrome-has-unwanted-outline-on-right-and-bottom

and the following code in our app is the cause:

```
    <Style x:Key="CustomWindowStyle" TargetType="{x:Type Window}">
        <Setter Property="Background" Value="{DynamicResource Window.Static.Background}" />
        <Setter Property="BorderBrush" Value="{DynamicResource Window.Static.Border}" />
        <Setter Property="Foreground" Value="{DynamicResource Window.Static.Foreground}" />
        <Setter Property="BorderThickness" Value="1" />
        <Setter Property="WindowStyle" Value="SingleBorderWindow" />
        <Setter Property="WindowChrome.WindowChrome">
            <Setter.Value>
                <!-- In order to have a window shadow, GlassFrameThickness needs to be non-zero which is annoying -->
                <!-- because the glass frame causes this weird flickering white border when resizing :( -->
                <!-- Seems like it's the best idea to just put Top to 1 and the rest on 0, because you'll probably notice it less -->
                <WindowChrome CaptionHeight="26" ResizeBorderThickness="6" CornerRadius="0" GlassFrameThickness="1 0 0 0"
                              NonClientFrameEdges="None" UseAeroCaptionButtons="False" />
            </Setter.Value>
        </Setter>
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="{x:Type Window}">
                    <Border Background="{TemplateBinding Background}" BorderBrush="{TemplateBinding BorderBrush}" BorderThickness="{TemplateBinding BorderThickness}">
                        <DockPanel>
                            <DockPanel Height="30" x:Name="titlebar" Background="{TemplateBinding BorderBrush}" VerticalAlignment="Top" Margin="0" DockPanel.Dock="Top">
                                <StackPanel Orientation="Horizontal" Grid.Column="0" HorizontalAlignment="Right" DockPanel.Dock="Right">
                                    <Button x:Name="btnMinimize" Focusable="False" Background="Transparent" BorderBrush="Transparent" Width="40" VerticalContentAlignment="Bottom" WindowChrome.IsHitTestVisibleInChrome="True" Click="Minimize_Event">
                                        <Rectangle Width="10" VerticalAlignment="Center" Margin="1 -24 0 0" Stroke="{DynamicResource ABrush.Glyph.Static}" StrokeThickness="2" />
                                    </Button>
                                    <Grid x:Name="ThingButtons">
                                        <Button x:Name="btnRestore" Focusable="False" Background="Transparent" BorderBrush="Transparent" Width="40"
                                                WindowChrome.IsHitTestVisibleInChrome="True" Click="AutoMinimize_Event">
                                            <Grid Width="12" Height="12">
                                                <Rectangle StrokeThickness="2" Stroke="{DynamicResource ABrush.Glyph.Static}" Margin="3,0,0,3" />
                                                <Rectangle StrokeThickness="2" Fill="{DynamicResource Window.Static.Border}" Stroke="{DynamicResource ABrush.Glyph.Static}" Margin="0,4,4,0" />
                                            </Grid>
                                        </Button>

                                        <Button x:Name="btnMaximize" Focusable="False" Background="Transparent" BorderBrush="Transparent" Width="40"
                                                WindowChrome.IsHitTestVisibleInChrome="True" Click="AutoMinimize_Event">
                                            <Grid Width="12" Height="12">
                                                <Rectangle StrokeThickness="2" Stroke="{DynamicResource ABrush.Glyph.Static}" Margin="0" />
                                            </Grid>
                                        </Button>
                                        <Button x:Name="btnWtfEvenLolol" Focusable="False" Background="Transparent" BorderBrush="Transparent" Width="40" WindowChrome.IsHitTestVisibleInChrome="True" Click="AutoMinimize_Event" Content="^"/>
                                    </Grid>
                                    <Button x:Name="btnClose" Focusable="False" Background="Transparent" BorderBrush="Transparent" Template="{DynamicResource CloseWindowButton}" Width="40" WindowChrome.IsHitTestVisibleInChrome="True" Click="CloseWindow_Event">
                                        <Grid Margin="0 1 0 0">
                                            <Line X1="0" Y1="0" X2="11" Y2="11" Stroke="{DynamicResource ABrush.Glyph.Static}" StrokeThickness="2" />
                                            <Line X1="0" Y2="0" Y1="11" X2="11" Stroke="{DynamicResource ABrush.Glyph.Static}" StrokeThickness="2" />
                                        </Grid>
                                    </Button>
                                </StackPanel>
                                <DockPanel Margin="0,0,5,0" HorizontalAlignment="Stretch">
                                    <Image HorizontalAlignment="Left" VerticalAlignment="Top" Margin="4,4,0,0" Source="{Binding Icon, RelativeSource={RelativeSource TemplatedParent}}" Height="24" />
                                    <TextBlock FontSize="13" Margin="5,3,0,3" VerticalAlignment="Center" HorizontalAlignment="Stretch" TextWrapping="NoWrap" Width="Auto" Foreground="{TemplateBinding Foreground}" Text="{Binding Title, RelativeSource={RelativeSource TemplatedParent}}" Grid.Column="1" TextAlignment="Left" />
                                </DockPanel>
                            </DockPanel>
                            <Grid>
                                <AdornerDecorator>
                                    <ContentPresenter/>
                                </AdornerDecorator>
                                <ResizeGrip x:Name="WindowResizeGrip" HorizontalAlignment="Right" IsTabStop="false" Visibility="Collapsed" VerticalAlignment="Bottom"/>
                            </Grid>
                        </DockPanel>
                    </Border>
                    <ControlTemplate.Triggers>
                        <MultiTrigger>
                            <MultiTrigger.Conditions>
                                <Condition Property="ResizeMode" Value="CanResizeWithGrip"/>
                                <Condition Property="WindowState" Value="Normal"/>
                            </MultiTrigger.Conditions>
                            <Setter Property="Visibility" TargetName="WindowResizeGrip" Value="Visible"/>
                        </MultiTrigger>
                        <Trigger Property="WindowState" Value="Maximized">
                            <Setter TargetName="btnRestore" Property="Visibility" Value="Visible"/>
                            <Setter TargetName="btnMaximize" Property="Visibility" Value="Collapsed"/>
                            <Setter TargetName="btnWtfEvenLolol" Property="Visibility" Value="Collapsed"/>
                        </Trigger>
                        <Trigger Property="WindowState" Value="Normal">
                            <Setter TargetName="btnRestore" Property="Visibility" Value="Collapsed"/>
                            <Setter TargetName="btnMaximize" Property="Visibility" Value="Visible"/>
                            <Setter TargetName="btnWtfEvenLolol" Property="Visibility" Value="Collapsed"/>
                        </Trigger>
                        <Trigger Property="WindowState" Value="Minimized">
                            <Setter TargetName="btnRestore" Property="Visibility" Value="Collapsed"/>
                            <Setter TargetName="btnMaximize" Property="Visibility" Value="Collapsed"/>
                            <Setter TargetName="btnWtfEvenLolol" Property="Visibility" Value="Visible"/>
                        </Trigger>
                        <Trigger Property="ResizeMode" Value="NoResize">
                            <Setter TargetName="ThingButtons" Property="Visibility" Value="Collapsed"/>
                            <Setter TargetName="btnMinimize" Property="Visibility" Value="Visible"/>
                        </Trigger>
                        <Trigger Property="ResizeMode" Value="CanMinimize">
                            <Setter TargetName="ThingButtons" Property="Visibility" Value="Visible"/>
                            <Setter TargetName="btnMinimize" Property="Visibility" Value="Visible"/>
                        </Trigger>
                        <Trigger Property="ResizeMode" Value="CanResizeWithGrip">
                            <Setter TargetName="ThingButtons" Property="Visibility" Value="Visible"/>
                            <Setter TargetName="btnMinimize" Property="Visibility" Value="Visible"/>
                        </Trigger>
                        <Trigger Property="WindowStyle" Value="ToolWindow">
                            <Setter TargetName="ThingButtons" Property="Visibility" Value="Collapsed"/>
                            <Setter TargetName="btnMinimize" Property="Visibility" Value="Collapsed"/>
                        </Trigger>
                        <Trigger Property="WindowStyle" Value="None">
                            <Setter TargetName="titlebar" Property="Visibility" Value="Collapsed"/>
                            <Setter Property="WindowChrome.WindowChrome">
                                <Setter.Value>
                                    <WindowChrome CaptionHeight="0" ResizeBorderThickness="6" CornerRadius="0" GlassFrameThickness="1 0 0 0" NonClientFrameEdges="None" UseAeroCaptionButtons="False" />
                                </Setter.Value>
                            </Setter>
                        </Trigger>
                    </ControlTemplate.Triggers>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
        <Style.Triggers>
            <Trigger Property="WindowState" Value="Maximized">
                <Setter Property="BorderThickness" Value="8" />
            </Trigger>
            <Trigger Property="WindowState" Value="Normal">
                <Setter Property="BorderThickness" Value="1" />
            </Trigger>
        </Style.Triggers>
    </Style>
```

**Comment by HiMarioLopez** [comment] 2023-12-04 15:55
fixed: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/pull/527

**Closed as completed by HiMarioLopez** 2023-12-04 15:55 UTC
Labels: bug, good first issue, low priority
