### ISSUE TITLE
Always active weapons (even when option is ticked off) and wrong amount of sets showing

### ISSUE THREAD

**Issue by modernfantastic** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#103] opened 2021-01-20 16:54 UTC
Hi, the tool seems to be showing weapons even though I have 30 of them at the moment and the threshold is set to 16, I made sure it's ticked off in always active tab but it's still happening after multiple resets and refreshes.

Also, the amount of sets that show up in the bottom left corner do not align with the actual number of sets available, it shows 10 for me when the items add up to 12.

**Comment by Emixamus** [comment] 2021-01-20 17:34
Same issue here.
![Issue CRE](https://user-images.githubusercontent.com/60391135/105212688-10101c00-5b4e-11eb-82ea-210bc4e2cf37.png)

**Comment by kosace** [comment] 2021-01-20 17:43
Hello,

1. i changed the numbers to the actual numbers
2. if its deactivated but not hiding correctly use a fresh filter because i changed the lootfilter writing

**Comment by modernfantastic** [comment] 2021-01-20 18:53
Sorry, I don't really know what you mean by "actual numbers"

and I used a fresh filter today but same thing happening with weapons still showing.

**Comment by kosace** [comment] 2021-01-20 18:58
i meant:

if you have 20 weapons and they are all 1h you can only make 10 sets. but if they all are 2h you can make 20. that means you cant be sure that you have enough weapons just by looking at the number. only when you have double the amount of the threshold it should 100% deactivate.

also: if that is the case and you have double the amount then link your lootfilter here pls so i can take a look

**Comment by modernfantastic** [comment] 2021-01-20 19:05
Ah right, that checks out, totally get you now, sorry for that. 

Is that tied to the sets showing for example "11 sets" instead of 14 that are available? i.e. is the variety of the 1h weapons the problem here?

edit: just to clarify I should normally have 14 sets available at the moment I believe but it says 11 bottom left/

**Comment by kosace** [comment] 2021-01-20 19:07
your threshold determines your maximum sets that get shown. if you have 12 threshold and 14 sets it will only show you 12 sets. 

otherwise its probably because you dont have enough low ilvl items. you could try to deactivate fill greedy if you mostly do higher tier maps

**Comment by modernfantastic** [comment] 2021-01-20 19:19
Thanks for responding so fast btw, however I have my threshold set to 16 and I just went throught the tab where i put my items into real quick and all of the items seem to be between the required 60-74 ilvl, highest being 74 atm, highest map i've done is t5

**Comment by modernfantastic** [comment] 2021-01-20 19:49
Disregard this whole thing, I'm just dumb, just now I realised that the rings you need 2x the amount too for the recipe, sorry for this topic, you can close it down or delete it. 

Thank you for your help and a great tool

**Comment by Emixamus** [comment] 2021-01-20 21:43
Well, I still got the problem... My quad is full of unidentified item, I can myself see at least 4 full sets, and the app still says I got zero. I've uninstalled twice now. I have no clue what the problem is

**Comment by HiMarioLopez** [comment] 2022-02-04 00:11
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.

**Closed as completed by HiMarioLopez** 2022-02-04 00:11 UTC
Labels: bug
