### ISSUE TITLE
[Bug] [Unsorted] *Brief synopsis of your issue*

### ISSUE THREAD

**Issue by nomis51** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#427] opened 2022-08-21 23:18 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Expected the application to not match wands/scepters with daggers (1 handed weapon), because they're are not compatible, resulting in the chaos recipe not working when vendoring.

# Current Behavior

Every 2-3 chaos recipe the application suggest me to grab a wand and a dagger or a scepter with a dagger to fill the weapon requirement for the vendor recipe, but it's not a valid match. 

It should not say that I have a weapon "set" (two 1h weapons) ready for the recipe when when there's a mismatch of wands/scepters and daggers. It should match daggers together and wands/scepters together.

e.g.

3 daggers and 2 wands in the stash = we have 2 set of weapons ready, not 3.

## Steps to Reproduce

1) Put a full set of rares in a tab
2) Make sure that you put a dagger and a wand for the weapon requirement
3) Change zone to update the API
4) Open up the stash tab
5) Click the `Stash` button on ECR overlay
6) Follow the instructions (everything seems fine, although it's not)
7) Try to vendor the items
8) You end up with a bunch of transmute shards instead of chaos orbs

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 1.6.0.2
* Operating System: Win 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice): Default settings with 1 tab set, provided account name, poesessid, client.txt and set the overlay opacity to 0. 

## Failure Logs

Don't know where they are, but I don't think it's relevant since it seems like just a logic problem while finding if we have or not enough weapons to fill up a set (or more)

**Comment by HiMarioLopez** [comment] 2022-08-21 23:34
Howdy, thanks for your issue report.

To clarify, the chaos recipe doesn't care about matching the specific class of 1-handed weapons. It only case that it's 2 1-handed weapons.

Here's a sample screenshot of a set with a wand and a one-handed sword.

![image](https://user-images.githubusercontent.com/23390842/185815598-d697c41c-f79e-45d8-a824-7a6ba376748a.png)

Then again with a wand + dagger combo

![image](https://user-images.githubusercontent.com/23390842/185815610-319071cb-b8ed-4f29-9f01-52a100a9aa31.png)

Closing this as it's working as intended. Thanks!

**Closed as completed by HiMarioLopez** 2022-08-21 23:34 UTC
Labels: bug

**Comment by nomis51** [comment] 2022-08-21 23:37
Weird, every single today I got a dagger and wand combo suggested by the app, the recipe failed at the vendor. Is there an order of vendoring or something that could make it fail to give 2 chaos ?
