### ISSUE TITLE
Overlay doesn't highlight any items

### ISSUE THREAD

**Issue by JoaoJola** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#362] opened 2022-05-15 20:33 UTC
Hello, I just started using your app and it worked fine for a couple hours until it stopped giving highlights to pick items to sell. I dont use the filter, its just the stash overlay that is giving issues. I use it in a Quad Tab. I send annexed a print screen with many obvious items to select for chaos recipe with no highlighted ones.
![no highlights](https://user-images.githubusercontent.com/105608740/168492737-bab60191-f9bb-47af-a95b-75a840344571.png)

**Comment by HiMarioLopez** [comment] 2022-05-17 17:29
For my notes:

Issue reported by user TurkeyS#8325 on the Discord server. Check #bug-reports chat logs for info. We tried doing general troubleshooting (reinstalling app, deleting settings, etc.)

Going to see if the set threshold is causing issues

**Comment by HiMarioLopez** [comment] 2022-05-17 19:21
Closing this for now to keep issue board clean. 

I let you know that we could  try increasing your set threshold from 5 -> 4

If you see something like this with a message for "Need lower level items!"
![image](https://user-images.githubusercontent.com/23390842/168893369-8c4d3d47-e557-4c44-a63a-2445086559c0.png)

Then it's working as intended. If not, we can re-open this.

**Closed as completed by HiMarioLopez** 2022-05-17 19:21 UTC
Labels: more details required, potential user error
