### ISSUE TITLE
[Bug] [Overlay] Setting for full set threshold not being honored

### ISSUE THREAD

**Issue by danplaseg** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#450] opened 2022-12-15 22:18 UTC
This might be related to issue [449](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/449), as it is happening to me at the same time as that one. Also it is possible this is related as well, or even a duplicate of [384](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/384), but I'm not totally sure, there's a lot going on there.

Basically it does not matter the number I put in the mentioned parameter, even 0 for automatic behavior:
![image](https://user-images.githubusercontent.com/30199883/207978966-a318fc1a-682b-4a37-b7c6-82097c4f353d.png)

sets count ~~go on randomly, even though some of them do get disabled~~ actually work for armor slot, but only for that one, like in this pic:
![image](https://user-images.githubusercontent.com/30199883/207979070-9e61ebc2-c364-4795-8d45-aa15e452aed9.png)

* Chaos Recipe Enhancer Version: 1.7.0
* Operating System: Windows 10

**Comment by Lukeghost** [comment] 2022-12-16 22:54
go to adavanced and check the box do not preserve low level item gear, this option fixed mine.

**Comment by danplaseg** [comment] 2022-12-16 23:12
Indeed this seems to be a workaround for the problem, thank you 👍, but the problem is still there nonetheless.

**Comment by Irfy** [comment] 2023-04-11 22:32
-1 This always worked as intended, it's just that players do not understand the advanced option (hover with the mouse over the option for a detailed description). The option should be checked by default, and unchecking it should be an advanced thing. If it is unchecked by default, **that**'s a problem. Voting to close as working-as-intended or whatever the resolution is :)

**Comment by HiMarioLopez** [comment] 2023-08-18 12:18
Likely resolved by https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/pull/485

open new issue if issue still persists

**Closed as completed by HiMarioLopez** 2023-08-18 12:18 UTC
Labels: bug
