### ISSUE TITLE
App Not respecting some set cap

### ISSUE THREAD

**Issue by Davst** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#358] opened 2022-05-15 12:41 UTC
currently I have sets at 12. Armors are disabled but not gloves or helms

They are not set to keep highlighting.. just.. nothing happens.

![image](https://user-images.githubusercontent.com/3330933/168473400-15256a64-da09-485d-bd1f-737619add4a7.png)

**Comment by box85** [comment] 2022-05-15 22:06
I'm having the same issue. Also the Sets counter stays at 0
![image](https://user-images.githubusercontent.com/28795388/168495825-e91b10b5-242a-417e-8a9b-d5f0f20307a9.png)

**Comment by HiMarioLopez** [comment] 2022-05-17 18:11
Looks to be a duplicate of #354 

I'm going to retitle that one and point y'all to the discussion happening on that issue.

**Closed as completed by HiMarioLopez** 2022-05-17 18:11 UTC
Labels: potential user error
